version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./sites-available:/etc/nginx/sites-available
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./ssl:/etc/ssl/private