version: '3'

networks:
  proxy-reverse:
    driver: bridge

services:
  nginx:
    image: nginx:1.21
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/etc/letsencrypt/:/etc/letsencrypt/:ro
      - ./config/etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./config/etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/:ro
      - ./config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/var/lib/letsencrypt/:/var/lib/letsencrypt/:ro
      - ./config/var/www/:/var/www/:ro
    networks:
      - proxy-reverse

  certbot:
    image: certbot/certbot:v1.23.0
    volumes:
      - ./config/etc/letsencrypt/:/etc/letsencrypt/:rw
      - ./config/var/lib/letsencrypt/:/var/lib/letsencrypt/:rw
      - ./config/var/www/:/var/www/:rw
    networks:
      - proxy-reverse
